# Generated by Django 4.0.3 on 2022-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_email_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='userna', max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
